name: zindeai_test
description: ZindeAI Router Worker Test Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # HTTP Client
  dio: ^5.7.0
  http: ^1.1.0
  
  # Supabase - Node.js API kullanıyoruz
  # supabase_flutter: ^2.8.0
  
  # UI Components
  cupertino_icons: ^1.0.8
  
  # State Management
  provider: ^6.1.2
  
  # JSON Serialization
  json_annotation: ^4.9.0
  
  # Media Display
  cached_network_image: ^3.4.1
  video_player: ^2.9.2
  
  # Utilities
  fluttertoast: ^9.0.0
  shimmer: ^3.0.0
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.2
  intl: ^0.20.2  # Tarih formatı için

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  json_serializable: ^6.8.0
  build_runner: ^2.4.13

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/
    - assets/meal_gold_10000.json
    - assets/meal_gold_10000_clean.json